#!/bin/bash

function build-box86() {
    cd ~
    sudo apt install build-essential wget cmake python3 gcc -y
    if [ -d box86 ]; then
        echo "box86 folder exist"
        sleep 1
        echo "Checking if box86 installed"
        sleep 1
        if [ ! -f /usr/local/bin/box86 ]; then
            echo "box86 no installed"
            sleep 1
            echo "building box86"
            sleep 1
            cd box86/build
            cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
            make -j3
            sudo make install
        else
            echo "box86 already"
        fi
        echo "done"
    else
        echo "box86 folder no exist"
        sleep 1
        if [ -f /usr/local/bin/box86 ]; then
            echo "but box86 installed"
            sleep 1
        else
            echo "checking for box86.txz"
            if [ -f box86.txz ]; then
                echo "Extracting exiting file"
                sleep 1
                tar xJvf box86.txz
                echo "building box86"
                sleep 1
                cd box86/build
                cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
                make -j3
                sudo make install
            else
                echo "Downloading box86"
                sleep 1
                wget https://github.com/ArieSR91/wine/raw/main/box86.txz
                tar xJvf box86.txz
                echo "building box86"
                sleep 1
                cd box86/build
                cmake .. -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
                make -j3
                sudo make install
            fi
            echo "done"
        fi
    fi
    cd ~
    return 0
}

function build-wine() {
    cd ~
    if [ -d wine ]; then
        echo "wine already"
        sleep 1
    else
        echo "extracting wine"
        sleep 1
        if [ -f wine.tgz ]; then
            tar -xzvf ~/wine.tgz
            rm ~/wine.tgz
        else
            echo "downloading wine"
            sleep 1
            wget https://twisteros.com/wine.tgz -O ~/wine.tgz
            echo "extracting wine"
            sleep 1
            tar -xzvf ~/wine.tgz
            rm ~/wine.tgz
        fi
        echo ""
    fi
    cd ~
    return 0
}

function configure-wine() {
    cd ~
    if [ ! -f /usr/local/bin/wine ]; then
        wget https://raw.githubusercontent.com/ArieSR91/wine/main/wine.sh
        sudo mv wine.sh /usr/local/bin/wine
    fi
    sleep 1
    if [ ! -f /usr/local/bin/winecfg ]; then
        sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
    fi

    if [ ! -f /usr/local/bin/wineboot ]; then
        sudo ln -s ~/wine/bin/wineboot /usr/local/bin/wineboot
    fi
    if [ ! -f /usr/local/bin/wineserver ]; then
        sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver
    fi
    sudo chmod 775 /usr/local/bin/wine /usr/local/bin/wineboot /usr/local/bin/winecfg /usr/local/bin/wineserver
    return 0
}

function show_help() {
    echo -e "Winebox by Arie-SR91

Usage: winebox [command] [options]

Command: box86          : Build and install box86
         wine           : Install wine
         configure      : Configure wine

Options: -h, --help     : Show this help screen
         -v, --version  : show the version

for more information visit https://github.com/ArieSR91
"
}

function show_version() {
    echo "1.1.1-SR"
}

case $1 in
    box86)
        build-box86
        ;;
    wine)
        build-wine
        ;;
    configure)
        configure-wine
        ;;
    -v | --version)
        show_version
        ;;
    -h | --help | *)
        show_help
        ;;
esac
